<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sav_network"
 *
 * Auto generated by SAV Library Kickstarter 20-07-19
 *
 ***************************************************************/
 
$EM_CONF[$_EXTKEY] = [
    'title' => 'SAV Network',
    'description' => 'Extension which displays a network by means of vis.js library',
    'category' => 'plugin',
    'author' => 'Laurent Foulloy',
    'author_email' => 'yolf.typo3@orange.fr',
    'author_company' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '9.5.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

?>